// <auto-generated />
using System;
using APIVideogames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIVideogames.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250713103339_VideogamePlatformTable")]
    partial class VideogamePlatformTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIVideogames.Model.Entities.Comentary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComentaryBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideogameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideogameId");

                    b.ToTable("Comentaries");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FoundationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("GenreId");

                    b.ToTable("Videogames");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.VideogamePlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("PlatformId", "VideogameId");

                    b.HasIndex("VideogameId");

                    b.ToTable("VideogamePlatforms");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Comentary", b =>
                {
                    b.HasOne("APIVideogames.Model.Entities.Videogame", "Videogame")
                        .WithMany("Comentaries")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Videogame", b =>
                {
                    b.HasOne("APIVideogames.Model.Entities.Developer", "Developer")
                        .WithMany("Videogames")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIVideogames.Model.Entities.Genre", "Genre")
                        .WithMany("Videogames")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.VideogamePlatform", b =>
                {
                    b.HasOne("APIVideogames.Model.Entities.Platform", "Platform")
                        .WithMany("Videogames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIVideogames.Model.Entities.Videogame", "Videogame")
                        .WithMany("Platforms")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Developer", b =>
                {
                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Genre", b =>
                {
                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Platform", b =>
                {
                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("APIVideogames.Model.Entities.Videogame", b =>
                {
                    b.Navigation("Comentaries");

                    b.Navigation("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
